ame: Deploy Blog

on: [push] # 当有新push时运行

jobs:
  build: # 一项叫做build的任务

    runs-on: ubuntu-latest # 在最新版的Ubuntu系统下运行
    
    steps:
    - name: Checkout # 将仓库内master分支的内容下载到工作目录
      uses: actions/checkout@v1 # 脚本来自 https://github.com/actions/checkout
      
    - name: Use Node.js 12.x # 配置Node环境
      uses: actions/setup-node@v1 # 配置脚本来自 https://github.com/actions/setup-node
      with:
        node-version: "12.x"
    
    - name: Setup Hexo env
      env:
        ACTION_DEPLOY_KEY: ${{ secrets.ACTION_DEPLOY_KEY }}
      run: |
        # set up private key for deploy
        mkdir -p ~/.ssh/
        echo "$ACTION_DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa # 配置秘钥
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        # set git infomation
        git config --global user.name 'lijifeng' # 换成你自己的邮箱和名字
        git config --global user.email '1229786829@qq.com'
        # install dependencies
        npm i -g hexo-cli # 安装hexo
        npm i
        npm install hexo-deployer-git
        npm i -S hexo-generator-search hexo-generator-json-content
        npm i -S hexo-renderer-stylus
        npm install hexo-generator-feed
        npm install hexo-generator-sitemap
    - name: Deploy
      run: |
        # publish
        hexo clean && hexo generate && hexo deploy # 执行部署程序
        
    # 以下是云开发的配置
    - name: Deploy static to Tencent CloudBase
      id: deployStatic
      uses: TencentCloudBase/cloudbase-action@v1.1.0
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./dist
      with:
        secretId: ${{ secrets.SECRET_ID }}
        secretKey: ${{ secrets.SECRET_KEY }}
        envId: ${{ secrets.ENV_ID }}
        staticSrcPath: ./public
